spring.application.name=mmbank

# Fazendo o bind das variáveis do .env para o DatabaseProperties
db.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB}
db.username=${POSTGRES_USER}
db.password=${POSTGRES_PASSWORD}
db.port=${POSTGRES_PORT:5432}

# Configurações do Spring Datasource (usando as propriedades validadas acima indiretamente)
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}